### ISSUE TITLE
cabal2arch can't parse dependency spec in 'email-validate'

### ISSUE THREAD

**Issue by peti** [archhaskell/cabal2arch#19]
The email-validate package specifies the following dependency: "parsec >= 3.0 || == 2.1.*". As far as I can tell, this would allow building the package with the version of parsec that we have in [extra]. Unfortunately, cabal2arch translates that spec into "parsec>=3.0", which causes pacman to refuse to build that package.

**Comment by remyoudompheng** [comment]
See how I solved this in my personal fork of the archlinux module: the cabal library accepts a list of dependency "hints" that can favour a particular version over another.

I've created a platform-provides.txt file that lists the packages of HP 2010.2 so that these versions are used with highest priority. May I push this ?

**Comment by magthe** [comment]
Rémy, which patch are you referring to?  Please provide a link.
